# Generated by Django 6.0.6 on 2026-07-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('official_name', models.CharField(blank=True, max_length=200)),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('iso3', models.CharField(max_length=3, unique=True)),
                ('flag_png', models.URLField()),
                ('flag_svg', models.URLField()),
                ('fifa_code', models.CharField(blank=True, help_text='Usually same as ISO3.', max_length=3)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
