# Generated by Django 6.0.6 on 2026-07-03 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('points', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kickoff', models.DateTimeField()),
                ('stage', models.CharField(choices=[('GRP', 'Group Stage'), ('R32', 'Round of 32'), ('R16', 'Round of 16'), ('QF', 'Quarter Final'), ('SF', 'Semi Final'), ('3RD', 'Third Place'), ('FIN', 'Final')], default='GRP', max_length=5)),
                ('prediction_deadline', models.DateTimeField()),
                ('is_locked', models.BooleanField(default=False)),
                ('country1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country1', to='api.country')),
                ('country2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country2', to='api.country')),
            ],
            options={
                'ordering': ['kickoff'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_time_country1', models.PositiveSmallIntegerField(default=0)),
                ('full_time_country2', models.PositiveSmallIntegerField(default=0)),
                ('half_time_country1', models.PositiveSmallIntegerField(default=0)),
                ('half_time_country2', models.PositiveSmallIntegerField(default=0)),
                ('goal_in_first_15', models.BooleanField(default=False)),
                ('both_teams_scored', models.BooleanField(default=False)),
                ('winning_method', models.CharField(choices=[('90', '90 Minutes'), ('ET', 'Extra Time'), ('PEN', 'Penalty Shootout')], default='90', max_length=3)),
                ('man_of_the_match', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_published', models.BooleanField(default=False)),
                ('points_awarded', models.BooleanField(default=False)),
                ('first_team_to_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='main.match')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goals_country1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goals_country2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('predicted_winner', models.CharField(blank=True, max_length=20)),
                ('full_time_country1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('full_time_country2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('half_time_country1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('half_time_country2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('first_team_to_score', models.CharField(blank=True, max_length=20)),
                ('goal_in_first_15', models.BooleanField(blank=True, null=True)),
                ('both_teams_scored', models.BooleanField(blank=True, null=True)),
                ('winning_method', models.CharField(blank=True, choices=[('90', '90 Minutes'), ('ET', 'Extra Time'), ('PEN', 'Penalty Shootout')], max_length=3)),
                ('man_of_the_match', models.CharField(blank=True, max_length=100)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'match')},
            },
        ),
    ]
