# Generated by Django 6.0.6 on 2026-07-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_prediction_predicted_goals_first_half_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points_of_rd16',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
